### PR TITLE
Add support for PHPUnit 10

### PR DESCRIPTION
**Pull request by emodric**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Related tickets | N/A
| License         | MIT

### CODE REVIEW

**Comment by emodric** [comment]
@lchrusciel This is ready for review now!

I'm not sure, however, how to fix failing builds with PHPStan that complain about extra arguments for `TestCase::_construct` on PHPUnit 10. Any suggestions?

**Comment by emodric** [comment]
@lchrusciel Any tips on this one how to proceed?

**Comment by lchrusciel** [comment]
Ah Edi, sorry for the long response time. A lot of thing are happening. I will proceed with it asap. Ping me on WebSummerCamp, Sylius or Symfony slack next time :)

**Comment by emodric** [comment]
No problem @lchrusciel ! Thanks for this!

**Pull request merged**
