### PR TITLE
Symfony 5 support

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Related tickets | 
| License         | MIT

Copied from https://github.com/lchrusciel/ApiTestCase/pull/163 cause I'm trying to fix it.

### CODE REVIEW

**Comment by lchrusciel** [comment]
Hey Loic! Thanks a lot for starting this effort, it is hard for me to find time to do it recently.

**Comment by loic425** [comment]
> Hey Loic! Thanks a lot for starting this effort, it is hard for me to find time to do it recently.

Yes, I've seen the previous pull request history, and I felt you need some help 😄 
I need some help too to configure the SampleControlller. When I configured it properly, the ThirdPartyApiClient Mock doesn't work... 😢

**Comment by lchrusciel** [comment]
It is a huge help already 🎉 I will do something about the mock

**Comment by loic425** [comment]
I've not commit this part, I use a config file instead.

```
framework:
    test: null
    secret: "secret"
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'

doctrine:
    dbal:
        driver: pdo_sqlite
        user: root
        password: ''
        path: '%kernel.cache_dir%/db.sqlite'

    orm:
        auto_mapping: false
        mappings:
            ApiTestCase:
                dir: '%kernel.project_dir%/app/config/doctrine'
                prefix: 'ApiTestCase\Test\Entity'
                alias: 'ApiTestCase'
                is_bundle: false
                type: 'yml'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ApiTestCase\Test\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']

    ApiTestCase\Test\Service\ThirdPartyApiClient:
        public: true
```

```
class SampleController extends AbstractController
    /** @var ThirdPartyApiClient */
    private $thirdPartyApiClient;

    public function __construct(ThirdPartyApiClient $thirdPartyApiClient)
    {
        $this->thirdPartyApiClient = $thirdPartyApiClient;
    }
    
    ....
}
```

SampleControllerJsonTest
```
    public function testGetProductInventoryFromThirdPartyApi(): void
    {
        $this->client->getContainer()->mock(ThirdPartyApiClient::class, ThirdPartyApiClient::class)
            ->shouldReceive('getInventory')
            ->once()
            ->andReturn($this->getJsonResponseFixture('third_party_api_inventory'))
        ;

        $this->client->request('GET', '/use-third-party-api/');

        $response = $this->client->getResponse();

        $this->assertResponse($response, 'use_third_party_api');
    }
```

**Pull request merged**
